name: File-Changed

on:
  pull_request:
    branches: [ master ]

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','
          fileOutput: ','
      - name: test
        run: |
          cat $HOME/files.csv